sudo systemd-resolve --status | grep 'DNS Servers' -A2
cat '/etc/resolv.conf'
sudo echo "# Generated by NetworkManager
nameserver 114.114.114.114
nameserver 1.1.1.1">'/etc/resolv.conf'
sudo systemd-resolve --status | grep 'DNS Servers' -A2
cat '/etc/resolv.conf'
sudo systemctl restart systemd-resolved
sudo resolvectl statistics
sudo resolvectl flush-caches